from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

_CC = _C

# ----------- Backbone -----------
_CC.MODEL.BACKBONE.FREEZE = False

# ------------- RPN --------------
_CC.MODEL.RPN.FREEZE = False
_CC.MODEL.RPN.ENABLE_DECOUPLE = False
_CC.MODEL.RPN.BACKWARD_SCALE = 1.0

_CC.MODEL.RPN.K_NUM = 4
_CC.MODEL.RPN.REG_LOSS_TYPE = "iou"
_CC.MODEL.RPN.REG_LOSS_WEIGHT = 1.0
_CC.MODEL.RPN.REG_SMOOTH_L1_BETA = 0.0
_CC.MODEL.RPN.LOC_LOSS_TYPE = "smooth_l1"
_CC.MODEL.RPN.LOC_LOSS_WEIGHT = 1.0
_CC.MODEL.RPN.LOC_SMOOTH_L1_BETA = 0.0
_CC.MODEL.RPN.IOU_THRESHOLDS_OBJECTNESS = [0.3, 0.7]
_CC.MODEL.RPN.POSITIVE_FRACTION_OBJECTNESS = 1.0
_CC.MODEL.RPN.NMS_THRESH_TEST = 0.5

# ------------- ROI --------------
_CC.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False
_CC.MODEL.ROI_HEADS.ENABLE_DECOUPLE = False
_CC.MODEL.ROI_HEADS.BACKWARD_SCALE = 1.0
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "ECFSODOutputETFLayers"
_CC.MODEL.ROI_HEADS.CLS_DROPOUT = False
_CC.MODEL.ROI_HEADS.DROPOUT_RATIO = 0.8
_CC.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7
_CC.MODEL.ROI_HEADS.SCORE_THRESH = 0.05
_CC.MODEL.ROI_HEADS.NMS_THRESH = 0.5
_CC.MODEL.ROI_HEADS.TOPK = 1000
# ------------- TEST -------------
_CC.TEST.PCB_ENABLE = False
_CC.TEST.PCB_MODELTYPE = 'resnet'
_CC.TEST.PCB_MODELPATH = ""
_CC.TEST.PCB_ALPHA = 0.50
_CC.TEST.PCB_UPPER = 1.0
_CC.TEST.PCB_LOWER = 0.05

# ------------ Other -------------
_CC.SOLVER.WEIGHT_DECAY = 5e-5
_CC.MUTE_HEADER = True

_CC.MODEL.CPLN = CN()
_CC.MODEL.CPLN.EMD_DIM = 256
_CC.MODEL.CPLN.DISTANCE_TYPE = "COS"
_CC.MODEL.CPLN.REPS_PER_CLASS = 1
_CC.MODEL.CPLN.ALPHA = 0.2
_CC.MODEL.CPLN.BETA = 0.8
_CC.MODEL.CPLN.IOU_THRESHOLD = 0.7
_CC.MODEL.CPLN.LOSS_WEIGHT = 1.0

_CC.MODEL.SEC = CN()
_CC.MODEL.SEC.ETF_RESIDUAL = True