_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/Path/to/ImageNet/Pretrain/Weight"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  PROPOSAL_GENERATOR:
    NAME: "ECFRPN"
  RPN:
    HEAD_NAME: "ECFRPNHead"
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    REG_LOSS_TYPE: "iou"
    REG_LOSS_WEIGHT: 1.0
    LOC_LOSS_TYPE: "smooth_l1"
    LOC_LOSS_WEIGHT: 1.0
    IOU_THRESHOLDS_OBJECTNESS: [0.3, 0.7]
    POSITIVE_FRACTION_OBJECTNESS: 1.0
    NMS_THRESH: 0.7
    NMS_THRESH_TEST: 0.5
  ROI_HEADS:
    NAME: "ECFSODROIHeads"
    NUM_CLASSES: 15
    ENABLE_DECOUPLE: True 
    BACKWARD_SCALE: 0.75
    SCORE_THRESH: 0.05
    NMS_THRESH: 0.7
    NMS_THRESH_TEST: 0.5
    TOPK: 50
  CPLN:
    EMD_DIM: 256
    ALPHA: 0.2
    BETA: 0.8
    DISTANCE_TYPE: "COS"
    REPS_PER_CLASS: 1
    IOU_THRESHOLD: 0.7
    LOSS_WEIGHT: 1.0
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('dior_trainval_base2',)
  TEST: ('dior_test_base2',)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  STEPS: (24000, 32000)
  MAX_ITER: 36000
  CHECKPOINT_PERIOD: 200000
  WARMUP_ITERS: 100
OUTPUT_DIR: "/Path/to/Output/Dir"